# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX package structure
android.useAndroidX=true

# Kotlin code style for this project
kotlin.code.style=official

# Enables namespacing of each library's R class
android.nonTransitiveRClass=true

# Opt-out of built-in Kotlin feature in AGP 9.3 to use Kotlin Gradle Plugin 2.2.x
android.builtInKotlin=false
android.newDsl=false

# Improves project import performance for large dependency trees
android.dependency.excludeLibraryComponentsFromConstraints=true
